const textsEng = {
  'header.title': 'SpiritualScience Institute',
  'header.nav.home': 'Home',
  'header.nav.about': 'About Us',
  'header.nav.products': 'Products',
  'header.nav.services': 'Services',
  'header.nav.classes': 'Classes',
  'header.nav.testimonials': 'Testimonials',
  'header.nav.contact': 'Contact Us',
  'footer.subtitle': '© 2024 SpiritualScience Institute all rights reserved',
  'home.hero.title': 'Discover Inner Harmony',
  'home.hero.subtitle': 'Avenir Light is a clean and stylish font favored by designers Lorem ipsum dolor sit amet consectetur adipiscing elit fermentum mauris accumsan nulla, enim platea eget fringilla suspendisse morbi mus proin magna fames mi, molestie venenatis nullam hendrerit augue neque aliquet netus libero sagittis. Iaculis hendrerit in vehicula vel curae, risus fames pulvinar porta euismod, nisl parturient tellus litora. Porttitor posuere nec per mauris vestibulum dui at nostra facilisis vulputate purus integer fermentum vivamus non, urna imperdiet praesent aptent libero class accumsan laoreet pretium hac montes conubia id.',
  'home.about.title': 'About Us',
  'home.about.subtitle': 'Embrace Spiritual Wellness',
  'home.about.content': 'Welcome to the Spiritual Science Institute, a sanctuary of spiritual soothing and feng shui practices in the heart of Hong Kong founded by Pallas Ng. We are dedicated to promoting harmony and balance through our services and products, designed to elevate your spiritual journey. Our clean, minimalist design is infused with positive energy and the vibrant hues of the seven chakra colors, creating a serene atmosphere for your well-being and enlightenment.',
  'home.about.button': 'Learn More',
  'home.products.title': 'Our Offerings',
  'home.products.subtitle': 'Everyone possesses unique energy, and we influence one another, generating new energy which directly impacts our emotions, physical well-being and overall fortune. We have unique at-home methods that allow you to harness the power of this new energy, promote auspiciousness, and achieve balance in various aspects of your life.',
  'home.products.loadMore.button': 'Load More',
  'shared.productGrid.quickView': 'Quick View',
  'shared.productGrid.buyNow.button': 'Buy Now',
  'shared.quickViewModal.quantity.label': 'Quantity: ',
  'shared.quickViewModal.buyNow.button': 'Buy Now',
  'shared.quickViewModal.viewDetails.link': 'View More Deatails',
  'productsPage.productDetails.productInfo.header': 'PRODUCT INFO',
  'productsPage.productDetails.shippingInfo.header': 'SHIPPING INFO',
  'productsPage.productDetails.shippingInfo.content': 'For shipping within Hong Kong, we provide free shipping for orders over $500. For orders under $500, a shipping fee of $20 applies. Additional fees apply for international shipping. Please contact us for details.',
  'home.services.title': 'Services',
  'home.services.readMore.button': 'Read More',
  'home.services.bookNow.button': 'Book Now',
  'servicePage.serviceDetails.bookNow.button': 'Book Now',
  'servicePage.serviceDetails.contactDetails.title': 'Contact Details',
  'servicePage.serviceDetails.contactDetails.phone': '852 9111 9111',
  'servicePage.serviceDetails.contactDetails.email': 'info@iching.com',
  'servicePage.serviceDetails.contactDetails.location': 'Hong Kong',
  'home.classes.title': 'Classes',
  'home.classes.subtitle': 'Wonder how to do it? Come and learn it yourselves',
  'classCard.bookNow.button': 'Book Now',
  'classCard.viewCourse.button': 'View Course',
  'home.testimonials.title': 'Testimonials',
  'home.testimonials.subtitle': 'The services provided by the Spiritual Science Institute have truly transformed my life. I have found inner peace and balance like never before.',
  'home.contactUs.title': 'Contact Us',
  'home.contactUs.phoneNumber': '852 6802 6168',
  'home.contactUs.email': 'pallasng@ichingspiritual.com',
  'home.contactUs.website': 'https://www.ichingspiritual.com',
  'home.contactUs.location': 'Hong Kong',
  'aboutUsPage.preTitle': 'The Full Story',
  'aboutUsPage.title': 'About Us',
  'aboutUsPage.subtitle': 'Everyone is a ball of energy. In our daily lives, we encounter others\' energies, and these energies intervene with one another, affecting how we perceive this world. Understanding these energies helps you stay positive and harvest the most out of your journey.',
  'aboutUsPage.ourMission.title': 'Our Mission',
  'aboutUsPage.ourMission.content': 'Pallas Ng founded SpiritualScience Institute to help everyone understand and enhance their energies. It is our mission that every person can find their own unique regions of happiness and satisfaction. When you stay in touch with your true energy, you can find harmony and strength.',
  'aboutUsPage.aboutPallas.title': 'About Pallas',
  'aboutUsPage.aboutPallas.content': 'Pallas graduated from the University of New South Wales in Australia, majoring in Psychology. Over the 19 years of her career, she held senior management positions at Cathay Pacific Airways and in freight forwarding and courier companies. With more than 14 years of experience in spiritual communication and fortune-telling, she specializes in:',
  'productsPage.header.title': 'All Products',
  'productsPage.header.subtitle': 'This is your category description. It\'s a great place to tell customers what this category is about, connect with your audience, and draw attention to your products.',
  'servicesPage.header.title': 'Our Services',
  'classesPage.header.title': 'Our Classes / Courses',
  'classesPage.header.subtitle': 'Have you ever wondered how does Fortune-telling work? Come and learn it yourselves! Having an instructor to teach you step-by-step of what you need to know. The best thing about this is that all our classes are unlimited to repeating taking classes you have taken.',
  'testimonialsPage.header.title': 'Testimonials',
  'testimonialsPage.header.subtitle': '"Listen what the others have to say walking down this journey"',
  'contactUsPage.header.title': 'Contact Us',
  'contactUsPage.header.subtitle': 'This is your Contact section paragraph. Encourage your reader to reach out with any questions, comments or to take a different action specific to your site.',
  'contactUsPage.successToaster': 'Your request to SpiritualScience Institute has been submitted successfully!',
  'contactUsPage.errorToaster': 'There\'s an error with your submission. Please try again later.',
  'contactUsPage.form.name': 'Name',
  'contactUsPage.form.email': 'Email',
  'contactUsPage.form.phoneNumber': 'Phone Number',
  'contactUsPage.form.phoneNumber.helperText': 'Please include country code if not in Hong Kong',
  'contactUsPage.form.message': 'Message',
  'contactUsPage.form.submit.button': 'Submit',
};