const textsEng = {
  'company.title': 'SpiritualScience Institute',
  'header.nav.home': 'Home',
  'header.nav.about': 'About Us',
  'header.nav.products': 'Products',
  'header.nav.dropdown.allProducts': 'All Products',
  'header.nav.dropdown.iChingCardsInstructions': 'I Ching Oracle Cards Guide Book',
  'header.nav.dropdown.iChingCardsExplanations': 'Explanations of I Ching Oracle Cards',
  'header.nav.services': 'Services',
  'header.nav.classes': 'Classes',
  'header.nav.testimonials': 'Testimonials',
  'header.nav.contact': 'Contact Us',
  'footer.subtitle': '© 2024 SpiritualScience Institute all rights reserved',
  'home.hero.title': 'Discover Inner Harmony',
  'home.hero.subtitle': 'Do you have experience that the same unfortunate things keep happening? Transform your life through personalized guidance in metaphysics, psychology, and holistic healing. Let us help you attract positive energy, overcome challenges, and discover the path to lasting happiness and fulfillment.',
  'home.about.title': 'About Us',
  'home.about.subtitle': 'Embrace Spiritual Wellness',
  'home.about.content.first.paragraph': 'If you want to change your life, you must begin by changing your thoughts and behaviors. Only by actively making these changes can you embrace a better future.',
  'home.about.content.second.paragraph': 'Welcome to the Spiritual Science Institute, a sanctuary of spiritual soothing and feng shui practices in the heart of Hong Kong founded by Pallas Ng. We are dedicated to promoting harmony and balance through our services and products, designed to elevate your spiritual journey.',
  'home.about.button': 'Learn More',
  'home.products.title': 'Our Offerings',
  'home.products.subtitle.first.paragraph': 'Everyone possesses unique energy, and we influence one another, generating new energy which directly impacts our emotions, physical well-being and overall fortune.',
  'home.products.subtitle.second.paragraph': 'We have unique at-home methods that allow you to harness the power of this new energy, promote auspiciousness, and achieve balance in various aspects of your life.',
  'home.products.loadMore.button': 'Load More',
  'home.services.title': 'Services',
  'home.services.readMore.button': 'Read More',
  'home.services.bookNow.button': 'Book Now',
  'home.classes.title': 'Classes',
  'home.classes.subtitle': 'Wonder how to do it? Come and learn it yourselves',
  'home.testimonials.title': 'Testimonials',
  'home.testimonials.subtitle': 'The services provided by the Spiritual Science Institute have truly transformed my life. I have found inner peace and balance like never before.',
  'home.contactUs.title': 'Contact Us',
  'home.contactUs.phoneNumber': '+852 6802 6168',
  'home.contactUs.email': 'pallasng@ichingspiritual.com',
  'home.contactUs.website': 'https://www.ichingspiritual.com',
  'home.contactUs.location': 'Hong Kong',
  'shared.productGrid.quickView': 'Quick View',
  'shared.productGrid.buyNow.button': 'Buy Now',
  'shared.quickViewModal.quantity.label': 'Quantity: ',
  'shared.quickViewModal.buyNow.button': 'Buy Now',
  'shared.quickViewModal.viewDetails.link': 'View More Deatails',
  'products.iChingCardsInstructions.title': 'I Ching Oracle Cards Guide Book',
  'products.iChingCardsInstructions.about.title': 'About I Ching Oracle Cards',
  'products.iChingCardsInstructions.about.content.p1': 'Many people have experienced the challenge of finding a traditional Feng Shui master for Feng Shui consultations, requiring appointments, and often coming at a high cost...',
  'products.iChingCardsInstructions.about.content.p2': 'Everyone possesses unique energy, and when we gather in shared environments, we influence one another, generating new energy. This phenomenon is known as Feng Shui energy, which directly impacts our emotions, physical well-being, career success, and overall fortune.',
  'products.iChingCardsInstructions.about.content.p3': 'Now, we introduce a unique method that utilizes the Fengshui Oracle and energy lamps, allowing you to harness the power of Feng Shui energy, promote auspiciousness, and achieve balance in various aspects of your life. The best part is, you can do it yourself without relying on others, and it is both effective and affordable.',
  'products.iChingCardsInstructions.about.content.p4': 'With our Fengshui Oracle and energy lamps, you can now easily enhance the Feng Shui energy of your living or working space, leading to an improved quality of life.',
  'products.iChingCardsInstructions.howTo.header': 'How to use I Ching Oracle Cards',
  'products.iChingCardsInstructions.instructions.title': 'How to use I Ching Oracle Cards',
  'products.iChingCardsInstructions.instructions.content.p1': 'The Fengshui Oracle, consisting of 64 hexagrams, can be used to consult on various matters ranging from daily to within a year.',
  'products.iChingCardsInstructions.instructions.content.p2': 'Areas of divination: Feng shui energy in the home and office, relationships, work and career, wealth, inner world, study, life direction, travel, health.',
  'products.iChingCardsInstructions.steps.title': 'Steps',
  'products.iChingCardsInstructions.steps.1': 'Choose a card layout.',
  'products.iChingCardsInstructions.steps.2': 'While shuffling the cards, meditate on your question and envision the possible scenarios for the specified time period, which can range from 3 to 12 months in the future.',
  'products.iChingCardsInstructions.steps.3': 'Once the shuffling is complete, intuitively draw cards and place them sequentially in the designated positions within the layout. During the card-drawing process, focus sincerely on the imagery related to your question. The Fengshui Oracle do not differentiate between upright and reversed positions.',
  'products.iChingCardsInstructions.steps.4': 'Place the drawn cards on the table, and the interpretation of the card layout is the answer to your question. Please refer to the " Fengshui Oracle Interpretation" guide for assistance in interpreting the cards.',
  'products.iChingCardsInstructions.steps.5': 'If the answer is unsatisfactory, you can draw an additional card as a solution. The Fengshui Oracle are not categorized as good or bad; they are considered either suitable or unsuitable.',
  'products.iChingCardsInstructions.steps.p1': 'Please note that closed-ended questions cannot be asked with the Fengshui Oracle. Avoid questions that "Yes or no?" "Good or bad?" Instead, focus on open-ended questions such as "How should I handle..." "What are the potential developments in the future?" "What are the circumstances surrounding this event?"',
  'products.iChingCardsInstructions.cardSpread.title': 'Card Spread',
  'products.iChingCardsInstructions.cardSpread.oneCardDivination.title': 'One-Card Divination Method',
  'products.iChingCardsInstructions.cardSpread.oneCardDivination.content': 'Suitable for obtaining random inspiration.',
  'products.iChingCardsInstructions.cardSpread.twoCardDivination.title': 'Two-Card Divination Method',
  'products.iChingCardsInstructions.cardSpread.twoCardDivination.content': 'Suitable for predicting scenarios with two stages or comparing two situations.',
  'products.iChingCardsInstructions.cardSpread.twoCardDivination.content.p1': 'Example 1: Current situation and future circumstances or developments.',
  'products.iChingCardsInstructions.cardSpread.twoCardDivination.content.p2': 'Example 2: Development of Company A compared to Company B.',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.title': 'Three-Card Divination Method',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.content.li1': 'Suitable for predicting scenarios with three stages or comparing three situations.',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.content.li2': 'Suitable for predicting scenarios involving a problem, its cause, and its outcome.',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.content.p1': 'Example 1: Present, past, and future.',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.content.p2': 'Example 2: Prospects of personal career development in Country A, Country B, and Country C.',
  'products.iChingCardsInstructions.cardSpread.threeCardDivination.content.p3': 'Example 3: The issue at hand, its cause, and the resulting outcome.',
  'products.iChingCardsInstructions.cardSpread.fengShuiDivination.title': 'Feng Shui Energy Divination Method',
  'products.iChingCardsInstructions.cardSpread.fengShuiDivination.content.li1': 'Draw nine cards, representing the floor plan of your home or office.',
  'products.iChingCardsInstructions.cardSpread.fengShuiDivination.content.li2': 'Choose one card to represent the main entrance in your floor plan and other places accordingly.',
  'products.iChingCardsInstructions.cardSpread.fengShuiDivination.content.li3': 'When negative energy is detected in a specific direction, an additional card can be drawn as a solution. Please note that a complete set of cards is required to draw the solution.',
  'products.iChingCardsInstructions.cardSpread.fengShuiDivination.content.li4': 'Place the solution card along with an energy lamp in the corresponding position in your physical living or working space to initiate a change in the Feng Shui energy.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.title': 'Chinese Astrology Divination Method',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li1': 'Suitable for predicting various aspects of fortune within the next twelve months.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2': 'Draw twelve cards, each representing the fortune in one of twelve areas.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.life': 'Life: 	Overall personal fortune and unexpected life events.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.parents': 'Parents: 	Relationships with parents and elders.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.psychic': 'Psychic: 	Mental well-being, psychological state, and inner cultivation.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.residence': 'Residence: Personal assets, living and working environment.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.career': 'Career: 	Personal work and interaction with superiors.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.friends': 'Friends: 	Relationships with subordinates and/or friends. Friends\' situations.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.travel': 'Travel: 	External image of individual, auspiciousness or adversity in travel and relocation.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.health': 'Health: 	Personal health and the strength of the internal organs.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.wealth': 'Wealth: 	Financial fortune and the flow of funds.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.children': 'Children: 	Situations of children and/or pets.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.spouse': 'Spouse: 	Spouse\'s situation and/or relationship dynamics.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li2.siblings': 'Siblings: 	Siblings\' situations and/or interactions with partners.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li3': 'Choose one card to represent the “Life”. When selecting the Life’s card, you can consider the current time or month.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li4': 'Distribute the drawn cards according to the positions of the twelve houses. Refer to the chart in the circular diagram below for the allocation of the twelve houses.',
  'products.iChingCardsInstructions.cardSpread.astrologyDivination.content.li5': 'If an unfavorable card is drawn, an additional card can be drawn as a solution.  Please be aware that a complete set of cards is necessary to draw the solution.',
  'products.iChingCardsInstructions.nextStepsGuide.text': 'For I Ching Oracle Cards interpretation and recommendations. Please visit ',
  'products.iChingCardsInstructions.nextStepsGuide.text.link': 'here.',
  'products.category.iChingCards.header': 'What are I Ching Oracle Cards',
  'products.category.subconsciousIntegration.about.header': 'What is Subconscious Integration Healing',
  'products.category.subconsciousIntegration.about.content.p1': 'Pallas\' Subconscious Integration Healing helps you reconcile with the parallel universe ✨ and attract what you desire into your life. It can treat physical illnesses, past traumas, emotional and psychological patterns, relationship issues, business concerns, and more‼️',
  'products.category.subconsciousIntegration.about.content.p2': 'No matter what changes you want to make, it can help you achieve them quickly and easily 🌈.',
  'products.category.subconsciousIntegration.demo.header': 'Subconscious Integration Healing Demo',
  'products.category.subconsciousIntegration.demo.content': 'Curious how it is done? Take a look at the Demo below and come try communicate to your subconsciousness.',
  'products.category.singingBowls.header': 'Take a peek at how singing bowls can heal',
  'products.iChingCardsExplanations.title': 'I Ching Oracle Cards Interpretation and Recommendations',
  'products.iChingCardsExplanations.subTitle': 'Check out what each card represents and how it can help you in your daily life',
  'products.iChingCardsExplanations.overview': 'Overview',
  'products.iChingCardsExplanations.relationships': 'Relationships',
  'products.iChingCardsExplanations.career': 'Career',
  'products.iChingCardsExplanations.wealth': 'Wealth',
  'products.iChingCardsExplanations.advice': 'Advice',
  'products.iChingCardsExplanations.search.placeholder': 'Search for a card by card number',
  'products.iChingCardsExplanations.search.errorMessage': 'No card found. Please enter a number between 1 and 64',
  'productsPage.productDetails.productInfo.header': 'PRODUCT INFO',
  'productsPage.productDetails.shippingInfo.header': 'SHIPPING INFO',
  'productsPage.productDetails.shippingInfo.content': 'For shipping within Hong Kong, we provide free shipping for orders over $500. For orders under $500, a shipping fee of $20 applies. Additional fees apply for international shipping. Please contact us for details.',
  'detailViewPage.contactDetails.title': 'Contact Details',
  'detailViewPage.contactDetails.phone': '+852 6802 6168',
  'detailViewPage.contactDetails.email': 'pallasng@ichingspiritual.com',
  'detailViewPage.contactDetails.location': 'Hong Kong',
  'classCard.bookNow.button': 'Book Now',
  'classCard.viewCourse.button': 'View Course',
  'aboutUsPage.preTitle': 'The Full Story',
  'aboutUsPage.title': 'About Us',
  'aboutUsPage.subtitle': 'Everyone is a ball of energy. In our daily lives, we encounter others\' energies, and these energies intervene with one another, affecting how we perceive this world. Understanding these energies helps you stay positive and harvest the most out of your journey.',
  'aboutUsPage.ourMission.title': 'Our Mission',
  'aboutUsPage.ourMission.content.first.paragraph': 'Pallas Ng founded SpiritualScience Institute to help everyone understand and enhance their energies. It is our mission that every person can find their own unique happiness and satisfaction.',
  'aboutUsPage.ourMission.content.second.paragraph': 'As a metaphysician, my role is to help you attract good fortune and avoid misfortune, guiding you to discover your greatest inner potential for a better life. As a psychological counselor, I can support you in confronting life’s challenges, reconciling with your inner self, and finding the most suitable attitude toward life. As a mind-body-spirit guide, I will assist you in enhancing your self-awareness, enabling your soul to achieve fulfillment and happiness. Through techniques such as Ba Zi, Feng Shui, I Ching Tarot divination, heart transmission, root energy restructuring, and singing bowl sound therapy, I aim to help you gain insight into yourself and open up a new path in life.',
  'aboutUsPage.aboutPallas.title': 'About Pallas',
  'aboutUsPage.aboutPallas.content.first.paragraph': 'Pallas graduated from the University of New South Wales in Australia, majoring in Psychology. Over the 19 years of her career, she held senior management positions at Cathay Pacific Airways and in freight forwarding and courier companies. With more than 14 years of experience in spiritual communication and fortune-telling, she specializes in:',
  'aboutUsPage.aboutPallas.content.list.item1': 'BaZi',
  'aboutUsPage.aboutPallas.content.list.item2': 'Feng Shui',
  'aboutUsPage.aboutPallas.content.list.item3': 'Palm Reading',
  'aboutUsPage.aboutPallas.content.list.item4': 'Face Reading',
  'aboutUsPage.aboutPallas.content.list.item5': 'Iching Fortune-telling / divination',
  'aboutUsPage.aboutPallas.content.list.item6': 'Subconscious Integration Healing',
  'aboutUsPage.aboutPallas.content.list.item7': 'Inner Child Spiritual Communication',
  'aboutUsPage.aboutPallas.content.list.item8': 'Singing Bowl Healing',
  'productsPage.header.title': 'All Products',
  'productsPage.header.subtitle': 'This is your category description. It\'s a great place to tell customers what this category is about, connect with your audience, and draw attention to your products.',
  'servicesPage.header.title': 'Our Services',
  'servicePage.serviceDetails.bookNow.button': 'Book Now',
  'classesPage.header.title': 'Our Classes / Courses',
  'classesPage.header.subtitle': 'Have you ever wondered how does Fortune-telling work? Come and learn it yourselves! Having an instructor to teach you step-by-step of what you need to know. The best thing about this is that all our classes are unlimited to repeating taking classes you have taken.',
  'classesPage.classDetails.bookNow.button': 'Book Now',
  'testimonialsPage.header.title': 'Testimonials',
  'testimonialsPage.header.subtitle': '"Listen what the others have to say walking down this journey"',
  'contactUsPage.header.title': 'Contact Us',
  'contactUsPage.header.subtitle': 'This is your Contact section paragraph. Encourage your reader to reach out with any questions, comments or to take a different action specific to your site.',
  'contactUsPage.successToaster': 'Your request to SpiritualScience Institute has been submitted successfully!',
  'contactUsPage.errorToaster': 'There\'s an error with your submission. Please try again later.',
  'contactUsPage.form.name': 'Name',
  'contactUsPage.form.email': 'Email',
  'contactUsPage.form.phoneNumber': 'Phone Number',
  'contactUsPage.form.phoneNumber.helperText': 'Please include country code if not in Hong Kong',
  'contactUsPage.form.message': 'Message',
  'contactUsPage.form.submit.button': 'Submit',
};

export default textsEng;